config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "home#top"

get "/users/new", to: "users#new", as: "user_new"
post "/users/create", to: "users#create", as: "user_create"
get "/user/sign_out", to: "users#sign_out", as: "user_sign_out"

get "/users/sign_in", to: "sessions#user_new", as: "user_sign_in"
post "/users/sign_in", to: "sessions#user_create", as: "user_session_create"
get "/users/index", to: "home#index", as: "user_index"

resources :study_records, only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
end

app/models/study_record.rb
class StudyRecord < ApplicationRecord
  attr_accessor :hour, :min
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX}
  validates :password_digest, presence: true, length: { minimum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only:[:index]
  before_action :no_need_to_authenticate!, only:[:top]

  def top
  end

  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  protect_from_forgery :except => [:session]
  before_action :no_need_to_authenticate!, only:[:user_new, :user_create]

  def user_new
    @user = User.new
  end

  def user_create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in_user user
      flash[:success] = 'ログインに成功しました'
      redirect_to user_index_url
    else
      flash[:danger] = 'ログインに失敗しました'
      render "user_new"
    end

  end

  def user_destroy
    sign_out_user
  end

end

app/controllers/study_records_controller.rb
class StudyRecordsController < ApplicationController

  def index
    @study_records = StudyRecord.all
  end

  def new
    @category = Category.where(user_id: current_user.id)
    @study_record = StudyRecord.new
  end

  def create
    study_record = StudyRecord.new(study_record_params)
    study_record.study_time = Time.at(hour = params[:study_record][:hour].to_i, min = params[:study_record][:min].to_i)

    if study_record.save
      flash[:success] = "勉強記録を保存しました"
      redirect_to user_index_url
    else
      flash[:danger] = "sippai"
      redirect_to new_study_record_url
    end
  end

  private
  def study_record_params
    params.require(:study_record).permit(:category_id, :title, :comment,  :user_id)
  end

end

app/controllers/users_controller.rb
# frozen_string_literal: true
class UsersController < ApplicationController
  before_action :no_need_to_authenticate!, only:[:new, :create]
  before_action :authenticate_user!, only:[:sign_out]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in_user @user
      flash[:success] = '新規登録が完了しました'
      redirect_to user_index_url
    else
      flash[:danger] = '新規登録に失敗しました'
      render 'new'
    end
  end

  def sign_out
    sign_out_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def sign_in_user(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def sign_in_user?
    !current_user.nil?
  end

  def sign_out_user
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_path
  end

  def authenticate_user!
    unless sign_in_user?
      flash[:danger] = 'ログインしてください'
      redirect_to root_path
    end
  end

  def no_need_to_authenticate!
    if sign_in_user?
      flash[:danger] = 'ログイン時にこの操作はできません'
      redirect_to user_index_url
    end
  end
end

app/helpers/study_records_helper.rb
module StudyRecordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= render partial: "layouts/header" %>
  <% if sign_in_user? %>
    <h1><%= current_user.name %></h1>
    <%= link_to "ログアウト", user_sign_out_url %>
    <%= link_to "勉強記録を追加", new_study_record_url %>
  <% end %>
  <% if @study_records.present? %>
    <% @study_records.each do |study_record| %>
      <p><%= study_record %></p>
    <% end %>
  <% end %>
<%= render partial: "layouts/footer" %>

app/views/home/top.html.erb
<%= render partial: "layouts/header" %>
<div class="top">
  <div class="top-layouts">
    <div class="top-heading">
      <p>STUDYLOGをはじめよう！</p>
    </div>
    <div class="auth-buttons">
      <%= link_to "新規登録", user_new_url, class:"auth-button top-auth-button" %>
      <%= link_to "ログイン", user_sign_in_url, class: "auth-button top-auth-button" %>
    </div>
  </div>
</div>
<%= render partial: "layouts/footer" %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-layout-danger">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-layouts">
    <div class="footer-logo">
      <%= image_tag 'logo.png', class: "logo" %>
    </div>
    <div class="menus">
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="header-layouts">
    <div class="header-logo">
      <%= image_tag 'logo.png', class: "logo" %>
    </div>
    <div class="menus">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Studylogs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-layout-<%= message_type %>"><p><%= message %></p></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/study_records/new.html.erb
<div class="study-record">
  <div class="study-record-wrapper">
    <div class="study_record-title">
      <p>学習記録を保存</p>
    </div>
    <div class="study-record-form">
        <%= form_for @study_record, url: {action: "create"}, class: "study-record-columns" do |f| %>
          <div class="form-group">
            <%= f.label :category, "Category", class:"form-label" %>
            <%= f.collection_select :category_id, @category, :id, :name, {}, class: "form-control" %>
          </div>
          <%= f.label :title, "Title", class:"form-label" %>
          <%= f.text_field :title, placeholder: "Title", class:"auth-form-password" %>

          <%= f.label :Hour, "Hour", class:"form-label" %>
          <%= f.text_field :hour, placeholder: "Hour", class:"auth-form-password" %>

          <%= f.label :Min, placeholder: "Min" %>
          <%= f.text_field :min, placeholder: "Min", class:"auth-form-password" %>

          <%= f.label :"Comment", placeholder: "Comment" %>
          <%= f.text_field :comment, placeholder: "Comment", class: "auth-form-password" %>

          <%= f.hidden_field :user_id, :value => current_user.id %>

        <%= f.submit "勉強を記録", class: "form-submit"%>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="auth-layout">
  <div class="auth-wrapper-layout">
    <h2 class="auth-title">新規登録</h2>
    <%= form_for @user, url: {action: "create"}, class: "auth-form"  do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
      <div class="label_form_wrapper">
        <%= f.label :name, "名前", class:"form-label" %>
        <%= f.text_field :name, placeholder: "name", class: "auth-form-name" %>
      </div>
      <div class="label_form_wrapper">
        <%= f.label :email, "E-mail", class:"form-label" %>
        <%= f.email_field :email, placeholder: "email", class: "auth-form-email" %>
      </div>
      <div class="label_form_wrapper">
        <%= f.label :password, "パスワード", class:"form-label" %>
        <%= f.password_field :password, placeholder: "password", class: "auth-form-password" %>
      </div>
      <%= f.submit "新規登録", class:"form-submit" %>
    <% end %>
  </div>
</div>